In [4]:
import pandas as pd
import numpy as np
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [5]:
train = pd.read_csv('../data/train.csv')

In [9]:
train.apply(lambda x: x.nunique())

Id        50999
Hazard       50
T1_V1        19
T1_V2        24
T1_V3         9
T1_V4         8
T1_V5        10
T1_V6         2
T1_V7         4
T1_V8         4
T1_V9         6
T1_V10        5
T1_V11       12
T1_V12        4
T1_V13        4
T1_V14        5
T1_V15        8
T1_V16       18
T1_V17        2
T2_V1       100
T2_V2        39
T2_V3         2
T2_V4        22
T2_V5         6
T2_V6         7
T2_V7         7
T2_V8         3
T2_V9        25
T2_V10        7
T2_V11        2
T2_V12        2
T2_V13        5
T2_V14        7
T2_V15       12
dtype: int64

In [30]:
a = np.arange(1, 7).reshape(3, 2)[:, np.newaxis, :]
b = np.arange(-1, 5).reshape(3, 2)[:, :, np.newaxis]
print(a)
print(b)
(a*b).reshape(3, -1)

[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[[-1]
  [ 0]]

 [[ 1]
  [ 2]]

 [[ 3]
  [ 4]]]


array([[-1, -2,  0,  0],
       [ 3,  4,  6,  8],
       [15, 18, 20, 24]])

In [49]:
c = pd.DataFrame(np.array([[1, 2], [1, 3], [2, 3], [2, 4], [3, 5], [3, 1]]))
d = c.copy()
d['new'] = d.groupby(0).transform(np.mean)
d.groupby(0).filter(lambda x: x.new>=3)
d

TypeError: filter function returned a Series, but expected a scalar bool

In [ ]:
"""
things to try:
xgb on all categorical data
linear on interaction of numerical and categorical
multiway encoding
https://gonewithsuperwind.wordpress.com/2014/08/07/kaggle-competition-past-solutions/
https://scholar.google.com/scholar?hl=en&q=kaggle&btnG=&as_sdt=1%2C33&as_sdtp=
"""